replicaCount: 1

image:
  repository: ghcr.io/horizon-school-of-digital-technologies/library
  pullPolicy: IfNotPresent
  tag: "20241018-012704"

service:
  type: ClusterIP
  port: 50051
  metricsport: 2112

ingress:
  enabled: true
  className: nginx
  hosts:
    - host: yassinenebli.horizon-workspaces.com
      paths:
        - path: /
          pathType: ImplementationSpecific

resources:
  limits:
    cpu: "50m"
    memory: "128Mi"
  requests:
    cpu: "50m"
    memory: "128Mi"

autoscaling:
  enabled: false
